apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: robot-fleet

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - backend.yaml
  - telemetry-consumer.yaml
  - simulator.yaml
  - frontend.yaml
