# All runtime secrets live in Secrets Manager and are injected into ECS
# task definitions by ARN (see compute.tf's backend_secrets/worker_secrets
# maps) — never as plain environment variables, and never committed to
# source control.
#
# Two of these (AI/Voyage API keys) can't be generated by Terraform — they
# come from Anthropic/Voyage AI accounts. Terraform creates the secret
# container with a "REPLACE_ME" placeholder so ECS tasks can still start
# (the app already handles a missing/invalid key gracefully — see
# backend/app/agent/llm_client.py and embeddings_client.py, both return a
# clean 503 rather than crashing); `lifecycle.ignore_changes` stops
# Terraform from ever overwriting a real value you set afterward via the
# CLI/console. See README "Secrets management" for the exact commands.

resource "random_password" "jwt_secret" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "db_credentials" {
  name                    = "${local.name_prefix}/db-credentials"
  recovery_window_in_days = local.is_prod ? 30 : 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id
  secret_string = jsonencode({
    username = module.database.username
    password = module.database.password
    host     = module.database.address
    port     = module.database.port
    dbname   = module.database.db_name
    # Fully-assembled URL, matching backend/app/database.py's DATABASE_URL
    # env var exactly — one secret key, one env var, no in-container
    # string-building needed.
    url = "postgresql://${module.database.username}:${module.database.password}@${module.database.address}:${module.database.port}/${module.database.db_name}"
  })
}

resource "aws_secretsmanager_secret" "redis_auth" {
  count                   = var.redis_transit_encryption_enabled ? 1 : 0
  name                    = "${local.name_prefix}/redis-auth"
  recovery_window_in_days = local.is_prod ? 30 : 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "redis_auth" {
  count     = var.redis_transit_encryption_enabled ? 1 : 0
  secret_id = aws_secretsmanager_secret.redis_auth[0].id
  secret_string = jsonencode({
    auth_token = module.cache.auth_token
    # backend/app/cache.py's REDIS_URL env var, fully assembled.
    url = "rediss://:${module.cache.auth_token}@${module.cache.primary_endpoint_address}:${module.cache.port}"
  })
}

resource "aws_secretsmanager_secret" "jwt_secret" {
  name                    = "${local.name_prefix}/jwt-secret"
  recovery_window_in_days = local.is_prod ? 30 : 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "jwt_secret" {
  secret_id     = aws_secretsmanager_secret.jwt_secret.id
  secret_string = random_password.jwt_secret.result
}

resource "aws_secretsmanager_secret" "ai_api_key" {
  name                    = "${local.name_prefix}/ai-api-key"
  recovery_window_in_days = local.is_prod ? 30 : 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "ai_api_key" {
  secret_id     = aws_secretsmanager_secret.ai_api_key.id
  secret_string = "REPLACE_ME"

  lifecycle {
    ignore_changes = [secret_string]
  }
}

resource "aws_secretsmanager_secret" "voyage_api_key" {
  name                    = "${local.name_prefix}/voyage-api-key"
  recovery_window_in_days = local.is_prod ? 30 : 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "voyage_api_key" {
  secret_id     = aws_secretsmanager_secret.voyage_api_key.id
  secret_string = "REPLACE_ME"

  lifecycle {
    ignore_changes = [secret_string]
  }
}
